name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test python API
    defaults:
      run:
        working-directory: ./sonarqube-scanner-maven/maven-basic
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
    - name: Run tests
      run: mvn clean verify
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
