name: API workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Test Java
    defaults:
      run:
        working-directory: ./sonarqube-scanner-maven
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Run tests1
      working-directory: ./sonarqube-scanner-maven/maven-basic
      run: mvn clean verify
    - name: Run tests2
      working-directory: ./sonarqube-scanner-maven/maven-multilingual
      run: mvn clean verify
    - name: Run tests3
      working-directory: ./sonarqube-scanner-maven/maven-multimodule
      run: mvn clean verify
    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
